"""
Hosts the frontend Web UI and handles API requests by cloning isolated sessions for each user.

Prerequisite: 
Requires the `data/master_session.json` generated by `create_master_session.py`.

This server handles the `/ask` endpoint, manages audio uploads, tracks per-user sessions
(cloning the master session for new users), and serves static files from the `public/` directory.

Usage Examples:
    # Start the server on the default port (8000)
    python src/server/server.py

Arguments (when run programmatically):
    port: The port number to listen on (default: 8000).
"""

import http.server
import socketserver
import json
import os
import logging
import sys
import threading
import urllib.parse
import mimetypes
import uuid
import time
import re
import base64
from typing import Dict, Any

# Add project root to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../')))
from src.utils.run_gemini import run_gemini, sync_session_to_cli
from src.utils.config import get_config, setup_logging
from src.utils.calc_stats import calculate_cost

logger = logging.getLogger("server")

# Global session state. Dictionary and lock to protect against concurrency issues.
chat_mapping: Dict[str, str] = {}
chat_mapping_lock = threading.Lock()

# Document ID to URL mapping
doc_index: Dict[str, str] = {}
doc_index_lock = threading.Lock()

def load_doc_index():
    """Parses data/master_knowledge_base.md to build doc_id -> url mapping."""
    global doc_index
    kb_path = os.path.join(os.path.dirname(__file__), '../../data/master_knowledge_base.md')
    if not os.path.exists(kb_path):
        logger.warning(f"Master knowledge base not found at {kb_path}. Links will not be translated.")
        return

    new_index = {}
    try:
        with open(kb_path, 'r', encoding='utf-8') as f:
            content = f.read()
            # Regex to find <document id="doc_N"> followed by <url>...</url>
            # Use dotall to match across lines
            matches = re.finditer(r'<document id="(doc_\d+)">\s*<url>(.*?)</url>', content, re.DOTALL)
            for m in matches:
                new_index[m.group(1)] = m.group(2).strip()
        
        with doc_index_lock:
            doc_index = new_index
        logger.info(f"Loaded {len(doc_index)} document references from master KB.")
    except Exception as e:
        logger.error(f"Failed to parse master KB index: {e}")

def translate_doc_links(text: str) -> str:
    """Replaces Markdown links targets like (doc_1) with actual URLs."""
    with doc_index_lock:
        if not doc_index:
            return text
            
    # Matches (doc_1), (doc_12) etc. only if inside a markdown link target area
    return re.sub(r'\]\((doc_\d+)\)', lambda m: f"]({doc_index.get(m.group(1), m.group(1))})", text)

def load_chat_mapping(mapping_file: str):
    """Loads session mappings from file into memory."""
    global chat_mapping
    with chat_mapping_lock:
        if os.path.exists(mapping_file):
            try:
                with open(mapping_file, 'r', encoding='utf-8') as f:
                    chat_mapping.update(json.load(f))
            except Exception as e:
                logger.error(f"Failed to load session mapping: {e}")

def save_chat_mapping(mapping_file: str):
    """Saves session mapping from memory to disk."""
    global chat_mapping
    with chat_mapping_lock:
        try:
            os.makedirs(os.path.dirname(mapping_file), exist_ok=True)
            with open(mapping_file, 'w', encoding='utf-8') as f:
                json.dump(chat_mapping, f)
        except Exception as e:
            logger.error(f"Failed to save session mapping: {e}")


class ThreadedHTTPServer(socketserver.ThreadingMixIn, socketserver.TCPServer):
    """Server extension allowing request handling in separate threads."""
    allow_reuse_address = True


class GeminiHandler(http.server.SimpleHTTPRequestHandler):
    """Manages chat requests and serving PDF/static files."""
    
    def do_GET(self):
        # Securely serve user audio files (only if the filename contains the current session's chatId)
        if self.path.startswith('/audio/'):
            filename = urllib.parse.unquote(self.path[len('/audio/'):])
            
            # Simple security check: Ensure the filename contains the chatId provided in query params
            query_params = urllib.parse.parse_qs(urllib.parse.urlparse(self.path).query)
            client_chat_id = query_params.get('chatId', [None])[0]
            
            if not client_chat_id or client_chat_id not in filename:
                logger.warning(f"Unauthorized audio access attempt: {filename} from {client_chat_id}")
                self.send_error(403, "Access denied: Unauthorized session")
                return

            audio_dir = os.path.join(os.path.dirname(__file__), '../../data/user_audio')
            safe_filename = os.path.basename(urllib.parse.urlparse(filename).path)
            file_path = os.path.abspath(os.path.join(audio_dir, safe_filename))
            
            if os.path.exists(file_path) and os.path.isfile(file_path):
                self.send_response(200)
                self.send_header('Content-type', 'audio/wav')
                self.end_headers()
                with open(file_path, 'rb') as f:
                    self.wfile.write(f.read())
                return
            else:
                self.send_error(404, "Audio file not found")
                return

        if self.path.startswith('/materialy/'):
            config = get_config()
            materialy_root = os.path.abspath(config['paths']['materialy_dir'])
            rel_path = urllib.parse.unquote(self.path[len('/materialy/'):])
            file_path = os.path.abspath(os.path.join(materialy_root, rel_path))
            
            if os.path.commonpath([materialy_root]) != os.path.commonpath([materialy_root, file_path]):
                logger.warning(f"Blocked attempt to access outside materials directory: {file_path}")
                self.send_error(403, "Access denied")
                return
            
            if os.path.exists(file_path) and os.path.isfile(file_path):
                self.send_response(200)
                mime_type, _ = mimetypes.guess_type(file_path)
                self.send_header('Content-type', mime_type or 'application/octet-stream')
                self.end_headers()
                with open(file_path, 'rb') as f:
                    self.wfile.write(f.read())
                return
            else:
                self.send_error(404, f"File not found: {rel_path}")
                return
        
        super().do_GET()

    def send_json_error(self, code, message):
        """Helper to send JSON errors instead of HTML pages."""
        self.send_response(code)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps({"error": message}).encode())

    def do_POST(self):
        if self.path == '/ask':
            try:
                content_length = int(self.headers['Content-Length'])
                post_data = self.rfile.read(content_length)
                request_json = json.loads(post_data)
                
                user_query = request_json.get('question')
                audio_base64 = request_json.get('audio')
                chat_id = request_json.get('chatId')
                
                if not user_query and not audio_base64:
                    self.send_json_error(400, "Missing query or audio")
                    return

                config = get_config()
                paths = config['paths']
                if "answer_model" not in config:
                    raise KeyError("Missing required 'answer_model' in config/config.json")
                model = config["answer_model"]
                master_session_file = paths.get('master_session_file')
                mapping_file = os.path.join(paths['sessions_dir'], 'chat_sessions.json')
                
                logger.info(f"Processing query for chatId {chat_id} (Audio: {bool(audio_base64)})")
                
                with chat_mapping_lock:
                    gemini_session_id = chat_mapping.get(chat_id)

                if not gemini_session_id:
                    if not master_session_file or not os.path.exists(master_session_file):
                        self.send_json_error(500, "Master Session file missing. Run create_master_session.py first.")
                        return
                    
                    new_gemini_id = str(uuid.uuid4())
                    with open(master_session_file, 'r', encoding='utf-8') as f:
                        master_data = json.load(f)
                    
                    master_data['sessionId'] = new_gemini_id
                    
                    # Direct project-local cloning
                    cloned_session_file = os.path.join(paths['sessions_dir'], "answering", f"session-cloned-{new_gemini_id[:8]}.json")
                    os.makedirs(os.path.dirname(cloned_session_file), exist_ok=True)
                    with open(cloned_session_file, 'w', encoding='utf-8') as f:
                        json.dump(master_data, f, indent=2, ensure_ascii=False)
                    
                    gemini_session_id = new_gemini_id
                    with chat_mapping_lock:
                        chat_mapping[chat_id] = gemini_session_id
                    save_chat_mapping(mapping_file)

                # Handle Audio
                gemini_files = []
                audio_url = None
                if audio_base64:
                    audio_dir = os.path.join(os.path.dirname(__file__), '../../data/user_audio')
                    os.makedirs(audio_dir, exist_ok=True)
                    timestamp = time.strftime("%Y-%m-%d_%H-%M-%S")
                    audio_filename = f"{timestamp}_{chat_id}.wav"
                    audio_path = os.path.join(audio_dir, audio_filename)
                    with open(audio_path, "wb") as audio_f:
                        audio_f.write(base64.b64decode(audio_base64))
                    gemini_files.append(audio_path)
                    audio_url = f"/audio/{audio_filename}?chatId={chat_id}"
                    if not user_query:
                        user_query = "Odpowiedz na pytanie zadane w nagraniu audio."

                # Run model
                start_time = time.time()
                answer, result_info, error = run_gemini(
                    model_id=model,
                    prompt=user_query,
                    session_folder="answering",
                    session_id=gemini_session_id,
                    files=gemini_files
                )
                duration = time.time() - start_time
                
                if error:
                    logger.error(f"Gemini API Error: {error}")
                    self.send_json_error(500, error)
                    return

                logger.info(f"Received answer for {chat_id} (Time: {duration:.1f}s)")
                
                # Stats
                raw_stats = result_info.get("stats", {})
                flattened_stats = {"duration": f"{duration:.1f}s", "input": 0, "output": 0, "thoughts": 0, "cached": 0, "cost": 0.0}
                try:
                    if "models" in raw_stats:
                        for model_name, mdata in raw_stats["models"].items():
                            t = mdata.get("tokens", {})
                            flattened_stats["input"] += t.get("input", 0)
                            flattened_stats["output"] += t.get("candidates", 0)
                            flattened_stats["thoughts"] += t.get("thoughts", 0)
                            flattened_stats["cached"] += t.get("cached", 0)
                    flattened_stats["cost"] = calculate_cost(model, flattened_stats["input"], flattened_stats["output"] + flattened_stats["thoughts"], flattened_stats["cached"])
                except Exception as stats_err:
                    logger.warning(f"Error compiling stats: {stats_err}")

                final_answer = translate_doc_links(answer)

                self.send_response(200)
                self.send_header('Content-type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({
                    "answer": final_answer,
                    "stats": flattened_stats,
                    "audioUrl": audio_url
                }).encode())
                
            except Exception as e:
                logger.exception("Internal Server Error")
                self.send_json_error(500, str(e))
        else:
            super().do_POST()

def run_server(port: int = 8000):
    setup_logging()
    config = get_config()
    mapping_file = os.path.join(config['paths']['sessions_dir'], 'chat_sessions.json')
    load_chat_mapping(mapping_file)
    load_doc_index()
    
    def handler_factory(*args, **kwargs):
        return GeminiHandler(*args, directory="public", **kwargs)
    
    logger.info(f"Starting ThreadedHTTPServer on port {port}...")
    with ThreadedHTTPServer(("", port), handler_factory) as httpd:
        httpd.serve_forever()

if __name__ == "__main__":
    run_server()
