"""
Merges individual JSON traces into a single, unified Markdown knowledge base, 
and then primes the LLM's context cache by creating a master 'Master Session'.

Prerequisite: 
Requires JSON trace files generated by `create_document_traces.py`.

Usage Examples:
    # Compile the master session from traces generated with a 200-token limit using Gemini 3 Flash Preview
    python src/processor/create_master_session.py data/traces/200_gemini-3-flash-preview

Arguments:
    dir     Positional argument. The directory containing the JSON trace subfolders to be compiled into the knowledge base.
"""

import os
import sys
import glob
import argparse
import urllib.parse
import json
import logging
import time
from typing import Dict, List, Any

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../')))
from src.utils.config import get_config, setup_logging
from src.utils.run_gemini import run_gemini

logger = logging.getLogger("create_master_session")

def create_master_session(target_dir: str) -> None:
    """
    Recursively scans the target directory for JSON trace files, builds the knowledge base,
    and initializes the Master Session for the AI.
    """
    config = get_config()
    if "base_url_prefix" not in config:
        raise KeyError("Missing required 'base_url_prefix' in config/config.json")
    base_url_prefix = config['base_url_prefix']
    
    # Search for JSON files only
    trace_files = glob.glob(os.path.join(target_dir, "**/*.json"), recursive=True)

    if not trace_files:
        logger.warning(f"No JSON trace files found in {target_dir}")
        return

    logger.info(f"Found {len(trace_files)} trace files. Compiling...")

    all_docs = []
    for f_path in trace_files:
        try:
            with open(f_path, 'r', encoding='utf-8') as f:
                doc_data = json.load(f)
                
            if doc_data.get("zawartosc"):
                all_docs.append(doc_data)
            else:
                logger.warning(f"Skipping {f_path} - No 'zawartosc' found.")
        except Exception as e:
            logger.error(f"Error parsing {f_path}: {e}")

    # Build two versions of the content: 
    # 1. Human-friendly (with URLs and IDs) for auditing and server lookup
    # 2. LLM-optimized (with IDs but NO URLs) to prevent hallucinations and save tokens
    
    current_time = time.strftime("%Y-%m-%d %H:%M:%S")
    
    human_kb_parts = [
        "# Baza Wiedzy FDDS\n\n",
        f"**Katalog źródłowy:** {target_dir}\n",
        f"**Data utworzenia:** {current_time}\n\n",
        "Ten dokument zawiera skondensowaną wiedzę z materiałów Fundacji Dajemy Dzieciom Siłę.\n\n"
    ]
    
    llm_kb_parts = [
        "# Baza Wiedzy FDDS\n\n",
        "Ten dokument zawiera skondensowaną wiedzę z materiałów Fundacji Dajemy Dzieciom Siłę.\n\n"
    ]

    for i, doc in enumerate(all_docs, 1):
        doc_id = f"doc_{i}"
        filename = os.path.basename(doc["source"])
        url = base_url_prefix + urllib.parse.quote(doc["source"].replace('\\', '/'))
        title = doc.get("tytul", filename)
        
        # Human version (Full data)
        human_kb_parts.append(f"<document id=\"{doc_id}\">\n")
        human_kb_parts.append(f"  <url>{url}</url>\n")
        human_kb_parts.append(f"  <tytul>{title}</tytul>\n")
        human_kb_parts.append(f"  <tresc>\n{doc['zawartosc']}\n  </tresc>\n")
        human_kb_parts.append(f"</document>\n\n")

        # LLM version (Optimized - No <url> tag)
        llm_kb_parts.append(f"<document id=\"{doc_id}\">\n")
        llm_kb_parts.append(f"  <tytul>{title}</tytul>\n")
        llm_kb_parts.append(f"  <tresc>\n{doc['zawartosc']}\n  </tresc>\n")
        llm_kb_parts.append(f"</document>\n\n")

    # Read and append live corrections if they exist
    correction_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../data/correction.txt'))
    if os.path.exists(correction_path):
        try:
            with open(correction_path, 'r', encoding='utf-8') as f:
                correction_content = f.read().strip()
            
            if correction_content:
                correction_section = f"\n\n# Bieżące Poprawki (Aktualizacje na żywo)\n\nPoniższe informacje to najnowsze poprawki, które mają najwyższy priorytet i nadpisują ewentualne sprzeczne informacje z powyższych dokumentów:\n\n{correction_content}\n"
                
                # Append as a plain section
                human_kb_parts.append(correction_section)
                llm_kb_parts.append(correction_section)
                
                logger.info("Successfully appended data/correction.txt to the knowledge base as a section.")
        except Exception as e:
            logger.error(f"Failed to read data/correction.txt: {e}")

    full_human_kb = "".join(human_kb_parts)
    full_llm_kb = "".join(llm_kb_parts)

    logger.info(f"Successfully compiled {len(all_docs)} documents into memory.")

    # 1. Save timestamped copy for history
    kb_debug_dir = os.path.join(os.path.dirname(__file__), '../../data/knowledge_bases')
    os.makedirs(kb_debug_dir, exist_ok=True)
    debug_filename = time.strftime("%Y-%m-%d_%H-%M-%S") + ".md"
    kb_debug_path = os.path.abspath(os.path.join(kb_debug_dir, debug_filename))
    with open(kb_debug_path, 'w', encoding='utf-8') as f:
        f.write(full_human_kb)
    logger.info(f"Saved debug copy of knowledge base to {kb_debug_path}")

    # 2. Save master_knowledge_base.md for server lookup
    master_kb_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../data/master_knowledge_base.md'))
    with open(master_kb_path, 'w', encoding='utf-8') as f:
        f.write(full_human_kb)
    logger.info(f"Saved master knowledge base to {master_kb_path}")

    # --- Step 2: Prime Master Session ---
    logger.info("Sending Knowledge Base to Gemini to create Master Session...")
    
    if "answer_model" not in config:
        raise KeyError("Missing required 'answer_model' in config/config.json")
    model = config["answer_model"]

    full_prompt = (
        "Jesteś oficjalnym asystentem Fundacji Dajemy Dzieciom Siłę (FDDS).\n"
        "Oto Twoja baza wiedzy (KNOWLEDGE BASE), zawierająca skondensowane informacje z dokumentów i scenariuszy:\n\n"
        f"{full_llm_kb}\n\n"
        "Zasady odpowiadania:\n"
        "1. Odpowiadaj na podstawie powyższej bazy wiedzy oraz kiedy musisz, ogólnej wiedzy o FDDS dostępnej publicznie.\n"
        "2. BEZWZGLĘDNIE podawaj źródło informacji używając formatu linku Markdown: [Tytuł Dokumentu](id) (np. [Nasz Dokument](doc_1)). To jedyny akceptowalny sposób powoływania się na dokumenty. Nie używaj formatu 'Tytuł (id)'.\n"
        "3. Jako Cel Linku (URL) używaj WYŁĄCZNIE identyfikatora z atrybutu 'id' przypisanego do danego dokumentu (np. doc_1, doc_2).\n"
        "4. Używaj tagów <tytul> do nazywania dokumentów w tekście.\n"
        "5. Odpowiadaj tylko na pytania związane z działalnością FDDS. Na niezwiązane tematy czy żarty odpowiadaj 'Istnieję by pomagać osobom potrzebującym informacji w zakresie działania FDDS. Nie marnuj moich zasobów. Są ograniczone i zabraknie ich dla tych, którzy naprawdę ich potrzebują.'  \n"
        "6. Ostatnia sekcja zawiera listę sprostowań ad. zdezaktualizowanych lub błędnych informacji w serwowanych dokumentach. Zawsze traktuj te informacje nadrzędnie w przypadku konfliktu z innymi danymi. Nigdy nie wspominaj i nie linkuj tej sekcji bezpośrednio. Mów tylko, że 'zgodnie z moją skorygowaną wiedzą jest tak a tak, lub informacje w dokumencie X Y są już nieaktualne'.\n"
        "7. Jeśli rozumiesz te zasady i bazę wiedzy, odpowiedz tylko jednym słowem: READY."
    )

    answer, metadata, error = run_gemini(
        model, 
        prompt=full_prompt, 
        session_folder="..", 
        session_name="master_session.json"
    )
    if error:
        logger.error(f"Error creating Master Session: {error}")
        return

    logger.info(f"Created Master Session: {metadata.get('session_id')}")
    if metadata.get('session_path'):
        logger.info(f"Master Session saved to {metadata.get('session_path')}")
    else:
        logger.warning("Could not find the generated session file to archive.")

if __name__ == "__main__":
    setup_logging()
    parser = argparse.ArgumentParser(description="Compile structured trace files into a master knowledge base and create Master Session.")
    parser.add_argument("dir", help="Directory containing the trace subfolder.")
    args = parser.parse_args()
    create_master_session(args.dir)
