import os
import json
import logging
import argparse
import sys
import urllib.parse
import shutil
import time
from typing import List, Dict, Any

# Add project root to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../')))
from gemini_cli_headless import run_gemini_cli_headless
from src.utils.config import get_config, setup_logging
from src.utils.hashes import get_or_create_hash_file

logger = logging.getLogger("master_session")

def create_master_session(trace_dir: str = None):
    """Compiles individual JSON traces into a unified KB and creates a cached session."""
    print(f"STEP 2/2: Building Knowledge Base and Session...", flush=True)
    
    config = get_config()
    
    if trace_dir is None:
        trace_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '../', config['paths']['traces_dir']))
        trace_dir = os.path.join(trace_root, f"{config['trace_length']}_{config['doc_tracing_model']}")
    
    docs_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '../', config['paths']['documents_dir']))
    base_url_prefix = config.get('base_url_prefix', '/documents/')
    
    print(f"Source folder: {docs_root}", flush=True)
    print(f"Traces folder: {trace_dir}", flush=True)

    all_docs = []
    
    # 1. Scan documents recursively
    for root, _, files in os.walk(docs_root):
        if '.hidden' in root: continue
        
        for file in files:
            if file.lower().endswith('.pdf') and not file.endswith('.hidden'):
                pdf_path = os.path.join(root, file)
                rel_pdf_path = os.path.relpath(pdf_path, docs_root)
                
                # 2. Get hash for the document
                file_hash = get_or_create_hash_file(pdf_path)
                if not file_hash: continue
                
                # 3. Look for trace by hash
                trace_path = os.path.join(trace_dir, f"{file_hash}.json")
                if os.path.exists(trace_path):
                    try:
                        with open(trace_path, 'r', encoding='utf-8') as f:
                            trace_data = json.load(f)
                            # Store with current relative path for URL generation
                            trace_data["current_rel_path"] = rel_pdf_path
                            all_docs.append(trace_data)
                    except Exception as e:
                        print(f"ERROR reading trace {trace_path}: {e}", flush=True)
                else:
                    print(f"WARNING: No trace found for: {rel_pdf_path}", flush=True)

    if not all_docs:
        print("ERROR: No documents with valid traces found. Aborting.", flush=True)
        return

    print(f"Compiling {len(all_docs)} documents into Markdown...", flush=True)

    # Build human and LLM versions of KB
    human_kb_parts = [
        "# Baza Wiedzy FDDS\n\n",
        f"**Katalog źródłowy:** {os.path.relpath(trace_dir, os.path.join(os.path.dirname(__file__), '../'))}\n",
        f"**Data utworzenia:** {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n",
        "Ten dokument zawiera skondensowaną wiedzę z materiałów Fundacji Dajemy Dzieciom Siłę.\n\n"
    ]

    llm_kb_parts = [
        "# INSTRUKCJA SYSTEMOWA\n",
        "Jesteś asystentką Bazy Wiedzy Fundacji Dajemy Dzieciom Siłę.\n",
        "ZASADA REFERENCJI: Kiedy korzystasz z informacji z konkretnego dokumentu, MUSISZ podać jego identyfikator w nawiasach kwadratowych, np. [doc_1], [doc_5].\n",
        "ZAKAZ PODAWANIA TYTUŁÓW: Nigdy nie podawaj tytułów dokumentów ani nie twórz własnych linków Markdown. Używaj WYŁĄCZNIE identyfikatorów [doc_N]. System zewnętrzny automatycznie zamieni je na poprawne nazwy i linki.\n\n",
        "# Baza Wiedzy FDDS\n\n",
        "Ten dokument zawiera skondensowaną wiedzę z materiałów Fundacji Dajemy Dzieciom Siłę.\n\n"
    ]

    for i, doc in enumerate(all_docs, 1):
        doc_id = f"doc_{i}"
        url = base_url_prefix + urllib.parse.quote(doc["current_rel_path"].replace('\\', '/'))
        
        # Use the title generated by the LLM during the tracing phase
        # Fallback to a cleaned filename if the title is missing
        fallback_title = os.path.splitext(doc.get("original_filename", "Dokument"))[0].replace('_', ' ').replace('-', ' ')
        title = doc.get("tytul", fallback_title)

        # Human version (Full data for post-processing)
        human_kb_parts.append(f"<document id=\"{doc_id}\">\n")
        human_kb_parts.append(f"  <url>{url}</url>\n")
        human_kb_parts.append(f"  <tytul>{title}</tytul>\n")
        human_kb_parts.append(f"  <tresc>\n{doc['zawartosc']}\n  </tresc>\n")
        human_kb_parts.append(f"</document>\n\n")

        # LLM version (Minimal - NO TITLE, NO URL to prevent hallucinations)
        llm_kb_parts.append(f"<document id=\"{doc_id}\">\n")
        llm_kb_parts.append(f"  <tresc>\n{doc['zawartosc']}\n  </tresc>\n")
        llm_kb_parts.append(f"</document>\n\n")

    # Read and append live corrections if they exist
    correction_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../data/correction.txt'))
    if os.path.exists(correction_path):
        try:
            with open(correction_path, 'r', encoding='utf-8') as f:
                correction_content = f.read().strip()

            if correction_content:
                print("Including live corrections...", flush=True)
                correction_section = f"\n\n# Bieżące Poprawki (Aktualizacje na żywo)\n\nPoniższe informacje to najnowsze poprawki, które mają najwyższy priorytet i nadpisują ewentualne sprzeczne informacje z powyższych dokumentów:\n\n{correction_content}\n"
                human_kb_parts.append(correction_section)
                llm_kb_parts.append(correction_section)
        except Exception as e:
            print(f"Failed to read corrections: {e}", flush=True)

    # Save Markdown versions
    kb_output_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../data/master_knowledge_base.md'))
    with open(kb_output_path, 'w', encoding='utf-8') as f:
        f.writelines(human_kb_parts)

    print(f"Knowledge Base saved: data/master_knowledge_base.md", flush=True)

    # Create Master Session for LLM
    master_prompt = "".join(llm_kb_parts)
    print(f"Creating Master Session for {config['answer_model']} (this may take 10-30s)...", flush=True)
    
    session = run_gemini_cli_headless(
        prompt=master_prompt,
        model_id=config["answer_model"]
    )
    
    master_session_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../', config['paths']['master_session_file']))
    os.makedirs(os.path.dirname(master_session_path), exist_ok=True)
    
    # Copy from CLI workspace to our data folder
    shutil.copy2(session.session_path, master_session_path)
    
    # Save stats for admin panel
    kb_stats = {
        "token_count": session.stats.get("inputTokens", 0),
        "doc_count": len(all_docs),
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "model": config["answer_model"],
        "trace_dir": os.path.relpath(trace_dir, os.path.join(os.path.dirname(__file__), '../'))
    }
    stats_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../data/kb_stats.json'))
    with open(stats_path, 'w', encoding='utf-8') as f:
        json.dump(kb_stats, f, indent=2)
    
    print(f"Sync complete! KB Size: {kb_stats['token_count']} tokens.", flush=True)
    print(f"Session cached: data/master_session.json", flush=True)

if __name__ == "__main__":
    setup_logging()
    parser = argparse.ArgumentParser(description="Compile structured trace files into a master knowledge base and create Master Session.")
    parser.add_argument("dir", nargs='?', help="Optional: Directory containing the trace subfolder. Defaults to config settings.")
    args = parser.parse_args()
    create_master_session(args.dir)
