"""
Hosts the frontend Web UI and handles API requests by cloning isolated sessions for each user.

Prerequisite: 
Requires the `data/master_session.json` generated by `create_master_session.py`.

This server handles the `/ask` endpoint, manages audio uploads, tracks per-user sessions
(cloning the master session for new users), and serves static files from the `public/` directory.

Usage Examples:
    # Start the server on the default port (8000)
    python src/start_server.py

Arguments (when run programmatically):
    port: The port number to listen on (default: 8000).
"""

import http.server
import socketserver
import json
import os
import logging
import sys
import threading
import urllib.parse
import mimetypes
import uuid
import time
import re
import base64
import shutil
import glob
from typing import Dict, Any

# Add project root to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../')))
from gemini_cli_headless import run_gemini_cli_headless
from src.utils.config import get_config, setup_logging
from src.utils.calc_stats import calculate_cost

# Load environment variables
from dotenv import load_dotenv
load_dotenv(os.path.join(os.path.dirname(__file__), '../config/.env'))

logger = logging.getLogger("server")

# Global session state. Dictionary and lock to protect against concurrency issues.
chat_mapping: Dict[str, str] = {}
chat_mapping_lock = threading.Lock()

# Document ID to URL mapping
doc_index: Dict[str, Dict[str, str]] = {}
doc_index_lock = threading.Lock()

def load_doc_index():
    """Parses data/master_knowledge_base.md to build doc_id -> url/title mapping."""
    global doc_index
    kb_path = os.path.join(os.path.dirname(__file__), '../data/master_knowledge_base.md')
    if not os.path.exists(kb_path):
        logger.warning(f"Master knowledge base not found at {kb_path}. Links will not be translated.")
        return

    new_index = {}
    try:
        with open(kb_path, 'r', encoding='utf-8') as f:
            content = f.read()
            # Regex to find <document id="doc_N"> followed by <url>...</url> and <tytul>...</tytul>
            # Use dotall to match across lines
            matches = re.finditer(r'<document id="(doc_\d+)">\s*<url>(.*?)</url>.*?<tytul>(.*?)</tytul>', content, re.DOTALL)
            for m in matches:
                new_index[m.group(1)] = {
                    "url": m.group(2).strip(),
                    "tytul": m.group(3).strip()
                }
        
        with doc_index_lock:
            doc_index = new_index
        logger.info(f"Loaded {len(doc_index)} document references from master KB.")
    except Exception as e:
        logger.error(f"Failed to parse master KB index: {e}")

def translate_doc_links(text: str) -> str:
    """Replaces document references like [doc_1] or [Title](doc_1) with actual Markdown links [Title](URL)."""
    with doc_index_lock:
        if not doc_index:
            return text

    def replacer_id_only(m):
        doc_id = m.group(1)
        doc_info = doc_index.get(doc_id)
        if doc_info:
            return f"[{doc_info['tytul']}]({doc_info['url']})"
        return m.group(0)

    def replacer_with_title(m):
        title = m.group(1)
        doc_id = m.group(2)
        doc_info = doc_index.get(doc_id)
        if doc_info:
            return f"[{title}]({doc_info['url']})"
        return m.group(0)

    # 1. Handle [Title](doc_1) -> [Title](URL)
    text = re.sub(r'\[([^\]]+)\]\((doc_\d+)\)', replacer_with_title, text)

    # 2. Handle [doc_1] -> [Real Title](URL)
    text = re.sub(r'\[(doc_\d+)\]', replacer_id_only, text)

    return text


def load_chat_mapping(mapping_file: str):
    """Loads session mappings from file into memory."""
    global chat_mapping
    with chat_mapping_lock:
        if os.path.exists(mapping_file):
            try:
                with open(mapping_file, 'r', encoding='utf-8') as f:
                    chat_mapping.update(json.load(f))
            except Exception as e:
                logger.error(f"Failed to load session mapping: {e}")

def save_chat_mapping(mapping_file: str):
    """Saves session mapping from memory to disk."""
    global chat_mapping
    with chat_mapping_lock:
        try:
            os.makedirs(os.path.dirname(mapping_file), exist_ok=True)
            with open(mapping_file, 'w', encoding='utf-8') as f:
                json.dump(chat_mapping, f)
        except Exception as e:
            logger.error(f"Failed to save session mapping: {e}")

cost_tracking: Dict[str, Any] = {"sessions": {}, "hours": {}, "days": {}}
cost_tracking_lock = threading.Lock()

def load_cost_tracking(filepath: str):
    """Loads cost tracking from file into memory."""
    global cost_tracking
    with cost_tracking_lock:
        if os.path.exists(filepath):
            try:
                with open(filepath, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    cost_tracking.update(data)
            except Exception as e:
                logger.error(f"Failed to load cost tracking: {e}")

def save_cost_tracking(filepath: str):
    """Saves cost tracking from memory to disk."""
    global cost_tracking
    with cost_tracking_lock:
        try:
            os.makedirs(os.path.dirname(filepath), exist_ok=True)
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(cost_tracking, f)
        except Exception as e:
            logger.error(f"Failed to save cost tracking: {e}")

class ThreadedHTTPServer(socketserver.ThreadingMixIn, socketserver.TCPServer):
    """Server extension allowing request handling in separate threads."""
    allow_reuse_address = True


class GeminiHandler(http.server.SimpleHTTPRequestHandler):
    """Manages chat requests and serving PDF/static files."""
    
    def do_GET(self):
        if self.path == '/correction':
            html_path = os.path.join(os.path.dirname(__file__), '../public/correction.html')
            if os.path.exists(html_path):
                self.send_response(200)
                self.send_header('Content-type', 'text/html; charset=utf-8')
                self.end_headers()
                with open(html_path, 'rb') as f:
                    self.wfile.write(f.read())
            else:
                self.send_error(404, "Correction HTML not found")
            return

        if self.path == '/api/correction':
            correction_path = os.path.join(os.path.dirname(__file__), '../data/correction.txt')
            if os.path.exists(correction_path):
                self.send_response(200)
                self.send_header('Content-type', 'text/plain; charset=utf-8')
                self.end_headers()
                with open(correction_path, 'rb') as f:
                    self.wfile.write(f.read())
            else:
                self.send_response(200)
                self.send_header('Content-type', 'text/plain; charset=utf-8')
                self.end_headers()
                self.wfile.write(b'')
            return

        if self.path == '/api/config':
            config = get_config()
            safe_config = {
                "audio_recording_timeout_s": config.get("audio_recording_timeout_s", 30)
            }
            self.send_response(200)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps(safe_config).encode('utf-8'))
            return

        # Securely serve user audio files (only if the filename contains the current session's chatId)
        if self.path.startswith('/audio/'):
            filename = urllib.parse.unquote(self.path[len('/audio/'):])
            
            # Simple security check: Ensure the filename contains the chatId provided in query params
            query_params = urllib.parse.parse_qs(urllib.parse.urlparse(self.path).query)
            client_chat_id = query_params.get('chatId', [None])[0]
            
            if not client_chat_id or client_chat_id not in filename:
                logger.warning(f"Unauthorized audio access attempt: {filename} from {client_chat_id}")
                self.send_error(403, "Access denied: Unauthorized session")
                return

            audio_dir = os.path.join(os.path.dirname(__file__), '../data/user_audio')
            safe_filename = os.path.basename(urllib.parse.urlparse(filename).path)
            file_path = os.path.abspath(os.path.join(audio_dir, safe_filename))
            
            if os.path.exists(file_path) and os.path.isfile(file_path):
                self.send_response(200)
                self.send_header('Content-type', 'audio/wav')
                self.end_headers()
                with open(file_path, 'rb') as f:
                    self.wfile.write(f.read())
                return
            else:
                self.send_error(404, "Audio file not found")
                return

        if self.path.startswith('/documents/'):
            config = get_config()
            documents_root = os.path.abspath(config['paths']['documents_dir'])
            rel_path = urllib.parse.unquote(self.path[len('/documents/'):])
            file_path = os.path.abspath(os.path.join(documents_root, rel_path))

            if os.path.commonpath([documents_root]) != os.path.commonpath([documents_root, file_path]):
                logger.warning(f"Blocked attempt to access outside materials directory: {file_path}")
                self.send_error(403, "Access denied")
                return            
            if os.path.exists(file_path) and os.path.isfile(file_path):
                self.send_response(200)
                mime_type, _ = mimetypes.guess_type(file_path)
                self.send_header('Content-type', mime_type or 'application/octet-stream')
                self.end_headers()
                with open(file_path, 'rb') as f:
                    self.wfile.write(f.read())
                return
            else:
                self.send_error(404, f"File not found: {rel_path}")
                return
        
        super().do_GET()

    def send_json_error(self, code, message):
        """Helper to send JSON errors instead of HTML pages."""
        self.send_response(code)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps({"error": message}).encode())

    def do_POST(self):
        if self.path == '/api/correction':
            try:
                content_length = int(self.headers['Content-Length'])
                post_data = self.rfile.read(content_length)
                request_json = json.loads(post_data)
                
                content = request_json.get('content', '')
                correction_path = os.path.join(os.path.dirname(__file__), '../data/correction.txt')
                
                with open(correction_path, 'w', encoding='utf-8') as f:
                    f.write(content)
                    
                # Parse master KB to find original trace folder
                kb_path = os.path.join(os.path.dirname(__file__), '../data/master_knowledge_base.md')
                source_dir = "data/traces/200_gemini-3-flash-preview" # Fallback
                if os.path.exists(kb_path):
                    with open(kb_path, 'r', encoding='utf-8') as f:
                        for line in f:
                            if line.startswith("**Katalog źródłowy:**"):
                                source_dir = line.split("**Katalog źródłowy:**")[1].strip()
                                break
                
                # Execute create_master_session.py
                import subprocess
                script_path = os.path.join(os.path.dirname(__file__), './create_master_session.py')
                result = subprocess.run([sys.executable, script_path, source_dir], capture_output=True, text=True)
                
                if result.returncode != 0:
                    logger.error(f"Error creating master session: {result.stderr}\n{result.stdout}")
                    self.send_json_error(500, "Błąd w aktualizacji wiedzy")
                    return
                
                # Reload document index
                load_doc_index()
                
                self.send_response(200)
                self.send_header('Content-type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({"success": True}).encode())
            except Exception as e:
                logger.error(f"Error saving corrections: {e}")
                self.send_json_error(500, "Błąd podczas zapisywania poprawek")
            return

        if self.path == '/ask':
            try:
                content_length = int(self.headers['Content-Length'])
                post_data = self.rfile.read(content_length)
                request_json = json.loads(post_data)
                
                user_query = request_json.get('question')
                audio_base64 = request_json.get('audio')
                chat_id = request_json.get('chatId')
                
                if not user_query and not audio_base64:
                    self.send_json_error(400, "Missing query or audio")
                    return

                config = get_config()
                paths = config['paths']
                if "answer_model" not in config:
                    raise KeyError("Missing required 'answer_model' in config/config.json")
                model = config["answer_model"]
                master_session_file = paths.get('master_session_file')
                mapping_file = os.path.join(paths['sessions_dir'], 'chat_sessions.json')
                
                logger.info(f"Processing query for chatId {chat_id} (Audio: {bool(audio_base64)})")
                
                limits = config.get("limits", {})
                session_limit = limits.get("session_usd", 0.05)
                hourly_limit = limits.get("hourly_usd", 0.50)
                daily_limit = limits.get("daily_usd", 2.00)

                current_hour = time.strftime("%Y-%m-%d:%H")
                current_day = time.strftime("%Y-%m-%d")

                with cost_tracking_lock:
                    session_cost = cost_tracking.get("sessions", {}).get(chat_id, 0.0)
                    hourly_cost = cost_tracking.get("hours", {}).get(current_hour, 0.0)
                    daily_cost = cost_tracking.get("days", {}).get(current_day, 0.0)

                if session_limit > 0 and session_cost >= session_limit:
                    self.send_response(200)
                    self.send_header('Content-type', 'application/json')
                    self.end_headers()
                    self.wfile.write(json.dumps({
                        "answer": f"⚠️ Przekroczono limit kosztów dla tej sesji ({session_limit} USD). Odśwież stronę, aby rozpocząć nową sesję.",
                        "stats": {"duration": "0.0s", "input": 0, "output": 0, "thoughts": 0, "cached": 0, "cost": 0.0},
                        "audioUrl": None
                    }).encode())
                    return

                if hourly_limit > 0 and hourly_cost >= hourly_limit:
                    self.send_response(200)
                    self.send_header('Content-type', 'application/json')
                    self.end_headers()
                    self.wfile.write(json.dumps({
                        "answer": f"⚠️ Przekroczono globalny limit godzinowy serwera ({hourly_limit} USD). Spróbuj ponownie później.",
                        "stats": {"duration": "0.0s", "input": 0, "output": 0, "thoughts": 0, "cached": 0, "cost": 0.0},
                        "audioUrl": None
                    }).encode())
                    return

                if daily_limit > 0 and daily_cost >= daily_limit:
                    self.send_response(200)
                    self.send_header('Content-type', 'application/json')
                    self.end_headers()
                    self.wfile.write(json.dumps({
                        "answer": f"⚠️ Przekroczono globalny limit dzienny serwera ({daily_limit} USD). Spróbuj ponownie jutro.",
                        "stats": {"duration": "0.0s", "input": 0, "output": 0, "thoughts": 0, "cached": 0, "cost": 0.0},
                        "audioUrl": None
                    }).encode())
                    return

                with chat_mapping_lock:
                    gemini_session_id = chat_mapping.get(chat_id)

                user_session_file = None
                if gemini_session_id:
                    user_session_file = os.path.join(paths['sessions_dir'], "answering", f"session-{gemini_session_id}.json")
                    if not os.path.exists(user_session_file):
                        # Try to find it if the filename differs (fallback)
                        matches = glob.glob(os.path.join(paths['sessions_dir'], "answering", f"*{gemini_session_id[:8]}*.json"))
                        if matches:
                            user_session_file = matches[0]
                        else:
                            user_session_file = None # Will trigger re-cloning

                if not user_session_file:
                    if not master_session_file or not os.path.exists(master_session_file):
                        self.send_json_error(500, "Master Session file missing. Run create_master_session.py first.")
                        return
                    
                    gemini_session_id = str(uuid.uuid4())
                    user_session_file = os.path.join(paths['sessions_dir'], "answering", f"session-{gemini_session_id}.json")
                    
                    with open(master_session_file, 'r', encoding='utf-8') as f:
                        master_data = json.load(f)
                    master_data['sessionId'] = gemini_session_id
                    
                    os.makedirs(os.path.dirname(user_session_file), exist_ok=True)
                    with open(user_session_file, 'w', encoding='utf-8') as f:
                        json.dump(master_data, f, indent=2, ensure_ascii=False)
                    
                    with chat_mapping_lock:
                        chat_mapping[chat_id] = gemini_session_id
                    save_chat_mapping(mapping_file)

                # Handle Audio
                gemini_files = []
                audio_url = None
                if audio_base64:
                    audio_dir = os.path.join(os.path.dirname(__file__), '../data/user_audio')
                    os.makedirs(audio_dir, exist_ok=True)
                    timestamp = time.strftime("%Y-%m-%d_%H-%M-%S")
                    audio_filename = f"{timestamp}_{chat_id}.wav"
                    audio_path = os.path.join(audio_dir, audio_filename)
                    with open(audio_path, "wb") as audio_f:
                        audio_f.write(base64.b64decode(audio_base64))
                    gemini_files.append(audio_path)
                    audio_url = f"/audio/{audio_filename}?chatId={chat_id}"
                    if not user_query:
                        user_query = "Odpowiedz na pytanie zadane w nagraniu audio."

                # Run model
                start_time = time.time()
                try:
                    session = run_gemini_cli_headless(
                        prompt=user_query,
                        model_id=model,
                        files=gemini_files,
                        session_to_resume=user_session_file
                    )
                # Copy updated session back to project
                    shutil.copy2(session.session_path, user_session_file)
                    
                    # Use stats populated by gemini_cli_headless wrapper
                    s = session.stats
                    with open(os.path.join(paths['sessions_dir'], 'debug_stats.json'), 'w') as f:
                        json.dump({"s": s, "raw": session.raw_data}, f)
                except Exception as e:
                    logger.error(f"Gemini CLI Error: {e}")
                    self.send_json_error(500, str(e))
                    return
                    
                duration = time.time() - start_time
                logger.info(f"Received answer for {chat_id} (Time: {duration:.1f}s)")
                
                # Stats
                flattened_stats = {
                    "duration": f"{duration:.1f}s", 
                    "input": s.get("inputTokens", 0), 
                    "output": s.get("outputTokens", 0), 
                    "thoughts": s.get("thoughtTokens", 0), 
                    "cached": s.get("cachedTokens", 0), 
                    "cost": 0.0
                }
                
                try:
                    flattened_stats["cost"] = calculate_cost(
                        model, 
                        flattened_stats["input"], 
                        flattened_stats["output"] + flattened_stats["thoughts"], 
                        flattened_stats["cached"]
                    )

                    # Update and save cost tracking
                    cost = flattened_stats["cost"]
                    with cost_tracking_lock:
                        if "sessions" not in cost_tracking: cost_tracking["sessions"] = {}
                        if "hours" not in cost_tracking: cost_tracking["hours"] = {}
                        if "days" not in cost_tracking: cost_tracking["days"] = {}
                        
                        cost_tracking["sessions"][chat_id] = cost_tracking["sessions"].get(chat_id, 0.0) + cost
                        cost_tracking["hours"][current_hour] = cost_tracking["hours"].get(current_hour, 0.0) + cost
                        cost_tracking["days"][current_day] = cost_tracking["days"].get(current_day, 0.0) + cost
                    
                    cost_file = os.path.join(paths['sessions_dir'], 'cost_tracking.json')
                    save_cost_tracking(cost_file)

                except Exception as stats_err:
                    logger.warning(f"Error compiling stats: {stats_err}")

                final_answer = translate_doc_links(session.text)

                self.send_response(200)
                self.send_header('Content-type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({
                    "answer": final_answer,
                    "stats": flattened_stats,
                    "audioUrl": audio_url
                }).encode())
                
            except Exception as e:
                logger.exception("Internal Server Error")
                self.send_json_error(500, str(e))
        else:
            super().do_POST()

def run_server():
    import argparse
    import subprocess
    import time

    parser = argparse.ArgumentParser(description="FDDS RAG Server")
    parser.add_argument("--port", type=int, default=8000, help="Port to listen on")
    parser.add_argument("--blocking", action="store_true", help="Run in foreground (blocking mode)")
    args = parser.parse_args()

    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '../'))
    log_file_path = os.path.join(project_root, f'logs/server_{args.port}.log')
    pid_file_path = os.path.join(project_root, f'data/run/server_{args.port}.pid')

    # If NOT blocking, we spawn the background process
    if not args.blocking:
        if os.path.exists(pid_file_path):
            with open(pid_file_path, 'r') as f:
                old_pid = f.read().strip()
                # Check if process actually exists (Windows specific check)
                try:
                    import ctypes
                    PROCESS_QUERY_INFORMATION = 0x0400
                    handle = ctypes.windll.kernel32.OpenProcess(PROCESS_QUERY_INFORMATION, False, int(old_pid))
                    if handle:
                        ctypes.windll.kernel32.CloseHandle(handle)
                        print(f"Server is already running on port {args.port} (PID: {old_pid})")
                        return
                except Exception:
                    pass

        print(f"Starting server on port {args.port} in background...")
        
        # Build command to run itself with --blocking
        cmd = [sys.executable, __file__, "--port", str(args.port), "--blocking"]
        
        os.makedirs(os.path.dirname(log_file_path), exist_ok=True)
        log_file = open(log_file_path, 'a', encoding='utf-8')
        
        # Use DETACHED_PROCESS flag on Windows
        creationflags = 0x00000008 if os.name == 'nt' else 0
        
        process = subprocess.Popen(
            cmd,
            stdout=log_file,
            stderr=subprocess.STDOUT,
            cwd=project_root,
            creationflags=creationflags,
            start_new_session=True # Cross-platform backgrounding
        )
        
        os.makedirs(os.path.dirname(pid_file_path), exist_ok=True)
        with open(pid_file_path, 'w') as f:
            f.write(str(process.pid))
        
        print(f"Server started (PID: {process.pid})")
        print(f"Logs: {log_file_path}")
        return

    # If blocking, we run the actual server logic
    setup_logging(level=logging.DEBUG) # Always DEBUG
    
    config = get_config()
    mapping_file = os.path.join(config['paths']['sessions_dir'], 'chat_sessions.json')
    load_chat_mapping(mapping_file)
    cost_file = os.path.join(config['paths']['sessions_dir'], 'cost_tracking.json')
    load_cost_tracking(cost_file)
    load_doc_index()
    
    def handler_factory(*args, **kwargs):
        return GeminiHandler(*args, directory="public", **kwargs)
    
    logger.info(f"Starting FDDS Server (PID: {os.getpid()}) on port {args.port}...")
    try:
        with ThreadedHTTPServer(("", args.port), handler_factory) as httpd:
            httpd.serve_forever()
    except KeyboardInterrupt:
        logger.info("Server stopped by user.")
    finally:
        if os.path.exists(pid_file_path):
            os.remove(pid_file_path)

if __name__ == "__main__":
    run_server()
